In [75]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [82]:
df = pd.read_csv('data/data_clean.csv', index_col=0, sep= ',', header=0)

# cast timestamp to datetime format
df.timestamp = pd.to_datetime(df.timestamp)
df.tail(50)

                timestamp  location      customer_id
24855 2019-09-06 21:46:00     fruit  2019-09-06_1502
24856 2019-09-06 21:47:00  checkout  2019-09-06_1497
24857 2019-09-06 21:47:00  checkout  2019-09-06_1502
24858 2019-09-06 21:47:00     dairy  2019-09-06_1503
24859 2019-09-06 21:47:00     fruit  2019-09-06_1504
24860 2019-09-06 21:48:00     fruit  2019-09-06_1494
24861 2019-09-06 21:48:00  checkout  2019-09-06_1501
24862 2019-09-06 21:48:00  checkout  2019-09-06_1504
24863 2019-09-06 21:48:00     fruit  2019-09-06_1505
24864 2019-09-06 21:48:00     dairy  2019-09-06_1506
24865 2019-09-06 21:48:00     dairy  2019-09-06_1507
24866 2019-09-06 21:48:00     dairy  2019-09-06_1508
24867 2019-09-06 21:49:00    spices  2019-09-06_1494
24868 2019-09-06 21:49:00     dairy  2019-09-06_1496
24869 2019-09-06 21:49:00    drinks  2019-09-06_1503
24870 2019-09-06 21:49:00     dairy  2019-09-06_1505
24871 2019-09-06 21:50:00     fruit  2019-09-06_1496
24872 2019-09-06 21:50:00     dairy  2019-09-06_1500
24873 2019-09-06 21:50:00  checkout  2019-09-06_1507
24874 2019-09-06 21:50:00  checkout  2019-09-06_1508
24875 2019-09-06 21:50:00    drinks  2019-09-06_1509
24876 2019-09-06 21:50:00    spices  2019-09-06_1510
24877 2019-09-02 21:53:00  checkout  2019-09-02_1430
24878 2019-09-02 21:53:00  checkout  2019-09-02_1433
24879 2019-09-02 21:53:00  checkout  2019-09-02_1437
24880 2019-09-02 21:53:00  checkout  2019-09-02_1439
24881 2019-09-02 21:53:00  checkout  2019-09-02_1440
24882 2019-09-02 21:53:00  checkout  2019-09-02_1441
24883 2019-09-02 21:53:00  checkout  2019-09-02_1443
24884 2019-09-02 21:53:00  checkout  2019-09-02_1445
24885 2019-09-02 21:53:00  checkout  2019-09-02_1446
24886 2019-09-02 21:53:00  checkout  2019-09-02_1447
24887 2019-09-02 21:53:00  checkout  2019-09-03_1411
24888 2019-09-02 21:53:00  checkout  2019-09-03_1422
24889 2019-09-02 21:53:00  checkout  2019-09-04_1520
24890 2019-09-02 21:53:00  checkout  2019-09-04_1527
24891 2019-09-02 21:53:00  checkout  2019-09-04_1528
24892 2019-09-02 21:53:00  checkout  2019-09-04_1529
24893 2019-09-02 21:53:00  checkout  2019-09-04_1530
24894 2019-09-02 21:53:00  checkout  2019-09-05_1527
24895 2019-09-02 21:53:00  checkout  2019-09-05_1532
24896 2019-09-02 21:53:00  checkout  2019-09-05_1533
24897 2019-09-02 21:53:00  checkout  2019-09-06_1494
24898 2019-09-02 21:53:00  checkout  2019-09-06_1496
24899 2019-09-02 21:53:00  checkout  2019-09-06_1500
24900 2019-09-02 21:53:00  checkout  2019-09-06_1503
24901 2019-09-02 21:53:00  checkout  2019-09-06_1505
24902 2019-09-02 21:53:00  checkout  2019-09-06_1506
24903 2019-09-02 21:53:00  checkout  2019-09-06_1509
24904 2019-09-02 21:53:00  checkout  2019-09-06_1510

### time each customer spent in the market:

In [77]:
unique_cust_ids= df['customer_id'].unique()
unique_cust_ids

array(['2019-09-02_1', '2019-09-02_2', '2019-09-02_3', ...,
       '2019-09-06_1508', '2019-09-06_1509', '2019-09-06_1510'],
      dtype=object)

In [78]:
minutes_spend_list = []

# loop through the customer id columnn:
for cust in df['customer_id'].unique():
    df_at = df[df['customer_id']==cust] 
    
    # get first and last timestamp for current customer_id
    first_occ = df_at.timestamp[:1].values 
    last_occ = df_at.timestamp[-1:].values
    # print(first_occ, last_occ)
    
    # calculate time diff
    timediff = (last_occ - first_occ)/60000000000 # nanoseconds to minutes
    
    #print('customer', cust ,'spend', timediff.tolist()[0], 'minute(s) in the supermarket') 
    minutes_spend_list.append(timediff.tolist()[0])

In [83]:
# for some reason, there are negative values (-5000 minutes)
minutes_spend_list = [item for item in minutes_spend_list if item >= 0]

In [84]:
average = sum(minutes_spend_list) / len(minutes_spend_list)
max_time = max(minutes_spend_list)
min_time = min(minutes_spend_list)

max_time, min_time, average

(52, 1, 6.2477447152282215)

In [85]:
def most_common(lst):
    return max(set(lst), key=lst.count)

most_common_time = most_common(minutes_spend_list)

print(
    'The average time customers spend in the supermarket is: \n', 
      round(average, 2), 'minutes \n', 
    'The maximum time customers spend in the supermarket is: \n',
      round(max_time, 2), 'minutes \n', 
    'The minimum time customers spend in the supermarket is: \n',
      round(min_time, 2), 'minute(s) \n', 
    'The most commom time customers spend in the supermarket is: \n',
      round(most_common_time, 2), 'minute(s)  \n', 
     )

The average time customers spend in the supermarket is:
 6.25 minutes
 The maximum time customers spend in the supermarket is:
 52 minutes
 The minimum time customers spend in the supermarket is:
 1 minute(s)
 The most commom time customers spend in the supermarket is:
 1 minute(s)